server:
  port: 7700
  tomcat.uri-encoding: utf-8

spring:
  application:
    name: service-tm
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5434/seata_test
    username: postgres
    password: postgres
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      cluster: default
#      server-addr: localhost:8848
#      namespace: public
#      group: DEFAULT_GROUP